version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - milvus
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - OLLAMA_HOST=http://host.docker.internal:11434  # Connects to local Ollama
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app-network

  milvus:
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  milvus_data:
