embedding_model: "all-MiniLM-L6-v2"
keyword_model: "all-MiniLM-L6-v2"
chunk_size: 500
chunk_overlap: 100
markdown_folder: "../docs"
milvus:
  host: "localhost"
  port: "19530"
collection: 
  name: "knowledge_base"
  schema:
    fields:
      - name: "id"
        data_type: "INT64"
        description: "Unique identifier for the document"
        is_primary: true
        auto_id: true
        required: true
      - name: "embedding"
        data_type: "FLOAT_VECTOR"
        description: "Embedding of the chunk"
        dim: 384  # Dimension for all-MiniLM-L6-v2
        required: true
      - name: "content"
        data_type: "String"
        description: "Plain text content of the chunk"
        required: true
      - name: "metadata"
        data_type: "JSON"
        description: "Metadata of the document"
        required: false
      - name: "keywords"
        data_type: "Array"
        description: "Keywords of the chunk"
        required: false
      - name: "created_at"
        data_type: "String"
        description: "Created at date of the record"
        required: true